function add(numbers){
    console.log(numbers)
    if(!numbers){
        return 0
    }
    let delimiters = /[;,%*:\s|+\\]/;
    // Splitting the entered string using split function on basis of delimiters
    let numArray = numbers.split(delimiters);
    // final num array is generated by parsing the numArray and checking whether it is a numnber or not and ignoring number above 1000
    let finalNumArray = numArray.map(num=> parseInt(num)).filter(num => !isNaN(num) && num < 1000)
    const negativeNumbers = numArray.filter(num => num<0);
    if(negativeNumbers.length){
        throw new Error(`Negative numbers are not allowed: ${negativeNumbers.join(",")}`);
        // Throw error for negative numbers
    }
    let sum = 0;
    for(num of finalNumArray){
        sum = sum+num;
    }
    console.log(sum)
    return sum;
}
    //Can be changed based on custom input
    let numbers = '\\\n,2;+|+\n4;8'
    add(numbers)

    module.exports = {add}
